stages:
- template: azure/stages.yml@templates
  parameters:
    setup:
      - script: ./scripts/init.sh

resources:
  repositories:
    - repository: templates
      type: github
      name: crate-ci/azure-pipelines
      endpoint: gnunicorn
